### ISSUE TITLE
Testing docs

### ISSUE THREAD

**Issue by Alexey-I** [Dmitry1987/vault-chrome-extension#3]
Please add short instructions on how to install this plugin into browser and test it.

**Comment by Razva** [comment]
+1 for this, no idea how to install it in Chrome.

**Comment by Dmitry1987** [comment]
hey sorry guys this project was long time dead, do you still need it?
if yes, I guess I can spend a few weekends rewriting it to Vue.js and new UI.
Seems like it's ranked well in google so it's worth maintaining it. 

![image](https://user-images.githubusercontent.com/9369080/58503940-786ee600-813e-11e9-9e08-b264681774ba.png)



lol 4th + 5th place for a github repo that is 3 years dead and were never updated except the day of the hackaton initial commit when it was created.... Google needs to seriously start refreshing their search ranking algorithms.... at least based on maintenance and updates of pages. I get a ton search results from 2008-2011, that's insane. A new smarter search engine might soon emerge and will take googles revenue away from them if they'll keep on sleeping.

**Comment by Razva** [comment]
> hey sorry guys this project was long time dead, do you still need it?
> if yes, I guess I can spend a few weekends rewriting it to Vue.js and new UI.
> Seems like it's ranked well in google so it's worth maintaining it.

Well...yeah...we're all obviously looking for improvements. :)

**Comment by Dmitry1987** [comment]
it was a single day hackathon project, it's fully working with minimal read/write/list mounts features, but I never took the time to package it properly or setup a build/release cycle. Will do soon.

**Comment by Dmitry1987** [comment]
The new version of this plugin is developed here! 
https://github.com/mulbc/vaultPass

I'll close this issue. And hopefully Google will index and rank the new location of the plugin well :) .
